### ISSUE TITLE
Import "requests_html" could not be resolved

### ISSUE THREAD

**Issue by deveapploper** [matheusfelipeog/worldometer#12]
how to solve this problem

[Running] python -u "f:\ggh\worldometer-master\worldometer\api.py"
Traceback (most recent call last):
  File "f:\ggh\worldometer-master\worldometer\api.py", line 103, in <module>
    from .core import Worldometer
ImportError: attempted relative import with no known parent package

[Done] exited with code=1 in 0.771 seconds

**Comment by matheusfelipeog** [comment]
Hi @deveapploper,

Thank you for opening this issue, and I apologize for the delay in responding to it.

I've made a significant update to this project to address most of the recurring issues. This update introduces a new API (the old one is deprecated and will be removed in the future), new datasets, and updated documentation.

If you are still interested in this package and the collected data, you can check it out in [version >=2.0.0 on PyPI](https://pypi.org/project/worldometer/).

If there are any other issues, please open them, and I will review them as soon as possible.
