### ISSUE TITLE
Issue with "sanitize_metrics" method.

### ISSUE THREAD

**Issue by MaiaPiko** [matheusfelipeog/worldometer#18]
code:

api.get_metric_of(label='computers_produced_this_year')

Errors:
..\worldoMeter\.venv\Lib\site-packages\worldometer\core.py", line 181, in __init__
    self._metrics = self.collect_metrics()
                    ^^^^^^^^^^^^^^^^^^^^^^
..\worldoMeter\.venv\Lib\site-packages\worldometer\core.py", line 305, in collect_metrics
    sanitized_metrics = self.sanitize_metrics(metric_list=metrics)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
..\worldoMeter\.venv\Lib\site-packages\worldometer\core.py", line 283, in sanitize_metrics
    found = re.search(r'[0-9,]+', metric).group()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

Looks like the error is originating from the "sanitize_metrics" method in the "core.py" file of the package.

**Comment by matheusfelipeog** [comment]
Hi @MaiaPiko,

Thank you for opening this issue, and I apologize for the delay in responding to it.

I've made a significant update to this project to address most of the recurring issues. This update introduces a new API (the old one is deprecated and will be removed in the future), new datasets, and updated documentation.

If you are still interested in this package and the collected data, you can check it out in [version >=2.0.0 on PyPI](https://pypi.org/project/worldometer/).

If there are any other issues, please open them, and I will review them as soon as possible.
