### ISSUE TITLE
Suggestion for adding temperature module

### ISSUE THREAD

**Issue by yangzi0802** [matheusfelipeog/worldometer#19]
First of all, thank you for this module and your hard work. Now I want a real-time temperature list of Global city to help the public understand climate change. If you have time, can you increase it?

**Comment by matheusfelipeog** [comment]
Hi @yangzi0802, thank you for opening this issue, and I apologize for the delay in responding.

Well, the scope of this project is limited to what is available on the website https://www.worldometers.info, which apparently does not provide information about temperature. I do not intend to deviate from this scope by fetching that information from elsewhere at the moment, so it's not a feature you will find here.
