### ISSUE TITLE
Navigation Timeout Exceeded Error

### ISSUE THREAD

**Issue by devAbreu** [matheusfelipeog/worldometer#20]
I am getting the following error when I try to run the `main.py` script:

```python
from worldometer import Worldometer

w = Worldometer()

w.what_is_here()
```
`Exception: Navigation Timeout Exceeded: 30000 ms exceeded.`

**Comment by matheusfelipeog** [comment]
Hi @devAbreu,

Thank you for opening this issue, and I apologize for the delay in responding to it.

I've made a significant update to this project to address most of the recurring issues. This update introduces a new API (the old one is deprecated and will be removed in the future), new datasets, and updated documentation.

If you are still interested in this package and the collected data, you can check it out in [version >=2.0.0 on PyPI](https://pypi.org/project/worldometer/).

If there are any other issues, please open them, and I will review them as soon as possible.
