### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by dileksunal** [matheusfelipeog/worldometer#21]
I want to use worldometer lib, but there is an import error in the below :

"Exception: HTTPSConnectionPool(host='www.worldometers.info', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"

When i try to import worldometer, i receivess the exception

**Comment by matheusfelipeog** [comment]
Hi @dileksunal,

Thank you for opening this issue, and I apologize for the delay in responding to it.

I've made a significant update to this project to address most of the recurring issues. This update introduces a new API (the old one is deprecated and will be removed in the future), new datasets, and updated documentation.

If you are still interested in this package and the collected data, you can check it out in [version >=2.0.0 on PyPI](https://pypi.org/project/worldometer/).

If there are any other issues, please open them, and I will review them as soon as possible.
